export { Home } from "./Home";
export { TvDetails } from "./TvDetails";
export { MovieDetails } from "./MovieDetails";
export { About } from "./About";
export { Search } from "./Search";
export { TopRatedMovies } from "./TopRatedMovies";
export { TopRatedTV } from "./TopRatedTV";
export { Favourites } from "./Favourites";
export { UsersList } from "./UsersList";
